version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    command: node server.js
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  esdata:
